apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "353"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"drec-api","namespace":"dev"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/name":"drec-api"}},"template":{"metadata":{"labels":{"app.kubernetes.io/name":"drec-api"}},"spec":{"containers":[{"envFrom":[{"secretRef":{"name":"drec-dev-env"}}],"image":"895706603967.dkr.ecr.eu-west-1.amazonaws.com/drec-api:dev-0.0.147","imagePullPolicy":"Always","name":"drec-api","ports":[{"containerPort":3040}]}]}}}}
  creationTimestamp: "2022-07-06T12:54:27Z"
  generation: 357
  name: drec-api
  namespace: dev
  resourceVersion: "273767772"
  uid: f4ebd6b3-7e4b-46aa-82ac-24302e8603b0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: drec-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-12-12T12:27:58+02:00"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: drec-api
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: drec-dev-env
          image: 895706603967.dkr.ecr.eu-west-1.amazonaws.com/drec-api:dev-0.0.147
          imagePullPolicy: Always
          name: drec-api
          ports:
            - containerPort: 3040
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: "2024-07-16T11:05:43Z"
      lastUpdateTime: "2024-07-16T11:05:43Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2024-09-24T09:07:01Z"
      lastUpdateTime: "2024-12-12T10:28:07Z"
      message: ReplicaSet "drec-api-689b6c6795" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
  observedGeneration: 357
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
