FROM node:16-alpine AS build
 
RUN apk --no-cache add bash
 
WORKDIR /dist/src/app
RUN npm cache clean --force
COPY . .
 
RUN npm i -g @microsoft/rush
RUN npm i -g pnpm
 
WORKDIR /dist/src/app/apps/drec-api
 
RUN npm install --legacy-peer-deps
RUN npm run migrate