apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: drec-api-migrate
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: drec-api-migrate
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drec-api-migrate
    spec:
      containers:
        - image: 895706603967.dkr.ecr.eu-west-1.amazonaws.com/drec-api-migrate:{{BUILD_NUMBER}}
          imagePullPolicy: Always
          name: drec-api-migrate
          envFrom:
            - secretRef:
                name: drec-dev-env
          ports:
            - containerPort: 3040
---
apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: drec-api-migrate-service
spec:
  ports:
    - port: 80
      targetPort: 3040
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: drec-api-migrate
