---
name: Idea / Feature request
description: Suggest an idea to improve Testing Form
title: "[Idea]: "
labels:
  - idea
  - feature-request
projects:
  - d-rec/2
body:
  - type: markdown
    attributes:
      value: >
        Thank you for sharing your ideas. Please take the time to provide as much
        detail as possible.
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: Describe what problem you would like to see solved.
      placeholder: I'm always frustrated when...
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: The solution
      description: Describe the solution(s) that you imagine for the aforementioned problem.
      placeholder: Changing XYZ would help because...
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternatives
      description: Are there any other solutions to that problem that you have considered?
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other helpful information or screenshots here.
    validations:
      required: false
