name: Docker Build

on:
  push:
    branches:
      - develop  # Trigger on pushes to the develop branch
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checks out the code

      - name: Build Docker image 
        run: docker build -t drec-origin -f apps/drec-api/Dockerfile apps/drec-api

      # List all Docker images built in this job
      - name: List all Docker images
        run: docker images
