name: Staging - Build, Push to ECR & Deploy to Kubernetes

on:
  push:
    branches:
      - stage
  workflow_dispatch:

jobs:
  build:
    uses: d-rec/drec-origin/.github/workflows/build-docker-ecr.yaml@stage
    with:
      environment: stage
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecr-registry: ${{ secrets.ECR_REGISTRY }}

  deploy:
    needs: build
    uses: d-rec/drec-origin/.github/workflows/deploy-ecr-k8s.yaml@stage
    with:
      environment: stage
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecr-registry: ${{ secrets.ECR_REGISTRY }}
