name: Build and Push to ECR

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      aws-access-key-id:
        required: true
      aws-secret-access-key:
        required: true
      aws-region:
        required: true
      ecr-registry:
        required: true
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          aws-region: ${{ secrets.aws-region }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: true
          registry-type: private

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ secrets.ecr-registry }}
          ECR_REPOSITORY: drec-api
          IMAGE_TAG: ${{ inputs.environment }}-${{ github.sha }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          docker build --build-arg SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -f apps/drec-api/Dockerfile apps/drec-api 

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
