name: Demo - Build, Push to ECR & Deploy to Kubernetes
# Check if the image can be build and deployed to the demo environment

on:
  push:
    branches:
      - demo
  workflow_dispatch:

jobs:
  build:
    uses: d-rec/drec-origin/.github/workflows/build-docker-ecr.yaml@demo
    with:
      environment: demo
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecr-registry: ${{ secrets.ECR_REGISTRY }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

  deploy:
    needs: build
    uses: d-rec/drec-origin/.github/workflows/deploy-ecr-k8s.yaml@demo
    with:
      environment: demo
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      ecr-registry: ${{ secrets.ECR_REGISTRY }}
