name: Code Quality

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Install tooling
        run: |
          npm i -g @microsoft/rush
          npm i -g pnpm@9

      - name: Install drec-origin
        run: |
          rush install

      - name: Run Prettier
        working-directory: apps/drec-api
        run: pnpm run prettier

  lint-eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Install tooling
        run: |
          npm i -g @microsoft/rush
          npm i -g pnpm@9

      - name: Install drec-origin
        run: |
          rush install

      - name: Run ESLint (error)
        working-directory: apps/drec-api
        run: pnpm run lint:error

      - name: Run ESLint (all)
        working-directory: apps/drec-api
        run: pnpm run lint

  check-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Install tooling
        run: |
          npm i -g @microsoft/rush
          npm i -g pnpm@9

      - name: Install drec-origin
        run: |
          rush install

      - name: Build drec-origin
        run: rush build --verbose

  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Install tooling
        run: |
          npm i -g @microsoft/rush
          npm i -g pnpm@9

      - name: Install drec-origin
        run: |
          rush install

      - name: Run Unit Test (all)
        working-directory: apps/drec-api
        run: pnpm run test:jest -- --maxWorkers=4

      - name: Run Code Coverage (all)
        working-directory: apps/drec-api
        run: pnpm run coverage:jest -- --maxWorkers=4
